# Gripper Configuration
config_gripper:
  gripper_model_name: "edrone"
  gripper_link_name: "base_frame"
  
  attachable_object_model_name: "cardoard_box"
  attachable_object_link_name: "link"

  logical_camera_topic_name: "/edrone/logical_camera"
